### ISSUE TITLE
Multiple copies of the UnityMainThreadDispatcher

### ISSUE THREAD

**Issue by mbger** [PimDeWitte/UnityMainThreadDispatcher#1]
Hi, 

I came across this when I searched for some sort of Singleton gameobject pattern which is persistent across scenes. I implemented it just the way you did, but had the problem that my object was created several times when I switched back and forth between scenes. After reading [this](http://answers.unity3d.com/questions/34185/dontdestroyonload-is-it-intended-behavior.html) I ended up removing the OnDestroyed()-method which clears the _instance field and added this to the Awake-method:
`void Awake () {

		if (_instance == null) {
			_instance = this;
			DontDestroyOnLoad (this.gameObject);
			//...
		} else {
			Destroy (this.gameObject);
		}
	}`

Maybe this is an issue for you, too (frankly, I don't know why the OnDestroy()-method was called on my gameobject)

**Comment by PimDeWitte** [comment]
Thank you for this. Adding it and pushing the new version. Sorry fo the inconvenience!

**Comment by PimDeWitte** [comment]
Fixed this in https://github.com/PimDeWitte/UnityMainThreadDispatcher/commit/ae76667b6504ee38ce8cdf480255c094ed5d38fd

**Comment by michaelbats** [comment]
Hi - I seem to be getting the same behaviour using the latest version here on github, not sure which part of it makes it do this. Here's a screenshot after loading between a few scenes -- showing  multiple instances of that object: https://i.imgur.com/1qaXJQH.png
