### ISSUE TITLE
The type or namespace name 'Task' could not be found

### ISSUE THREAD

**Issue by cdr9042** [PimDeWitte/UnityMainThreadDispatcher#16]
I got this error: The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?)

I'm using Unity 2019.3, .NET 4.x. Adding "using System.Threading.Tasks;" seems to fix this

**Comment by DamianMehers** [comment]
Seems like I forgot to include the appropriate "using" in my PR when I added this change.  I'll update it.
