### ISSUE TITLE
Is this usable in android/iOS?

### ISSUE THREAD

**Issue by szymon-kazmierczak** [PimDeWitte/UnityMainThreadDispatcher#20]
Hello, great project and i love using it for UI testing. I noticed, however, that when i run my tests on standalone android and iOS, that the following error shows up

`Error Message: System.Exception : UnityMainThreadDispatcher could not find the UnityMainThreadDispatcher object. Please ensure you have added the MainThreadExecutor Prefab to your scene.`
Was wondering if its something in my configuration or if this is not meant to be used in android/ios

**Comment by Novack** [comment]
Works perfect on Android, we have been using it without issues.

**Comment by szymon-kazmierczak** [comment]
Perfect, thank you! I'll try and fix it 👍 :D
