### ISSUE TITLE
Dispatcher cannot be found on every other scene load

### ISSUE THREAD

**Issue by rhysp** [PimDeWitte/UnityMainThreadDispatcher#3]
I have two scenes in my game. If I keep the `UnityMainThreadDispatcher` GameObject in the one scene where I (currently) require it, the scene will successfully load. If I switch scenes (via `UnityEngine.SceneManagement.SceneManager.LoadScene(...)` to my other scene, and then return to the dispatcher-driven scene, every alternating time I return to the scene I get the following error:

    System.Exception: UnityMainThreadDispatcher could not find the UnityMainThreadDispatcher object. Please ensure you have added the MainThreadExecutor Prefab to your scene.

I can see the dispatcher in my hierarchy, even on these erroneous scene loads.

Note that, toggling scenes again will load successfully, until the next change. I have also tried to include the dispatcher in both scenes, which causes neither to work correctly.

Removing `Destroy (this.gameObject);` in the `Awake` conditional will resolve this, but afraid I might not understand the need for this and it may have side-effects (GC?)

**Comment by PimDeWitte** [comment]
So, it should be safe to remove the Destroy() method because we are adding it to DoNotDestroy anyways. I have done so in https://github.com/PimDeWitte/UnityMainThreadDispatcher/blob/master/UnityMainThreadDispatcher.cs

just use that script and try again

Cheers!

**Comment by PimDeWitte** [comment]
Actually, just realized we added that because it was causing multiple instances of the object.

Since it's all static, it doesn't matter where the instance of the object lives, as long as "a" class is alive within "a" scene. I have added a check to make sure it always destroys the object in the previous scene.

Cheers

https://github.com/PimDeWitte/UnityMainThreadDispatcher/blob/master/UnityMainThreadDispatcher.cs

**Comment by PimDeWitte** [comment]
Please verify it and let me know if that fixes it btw.

**Comment by rhysp** [comment]
Thanks for looking into it @PimDeWitte, but after testing this new code my scene errors reverted back to the erroneous state, same error.

**Comment by PimDeWitte** [comment]
Ok, try removing the destroy for now and I willl look into it - let me know if removing the destroy works. Since the queue is static you should not have too many issues. GC shouldn't delete it.

**Comment by rhysp** [comment]
Removing the `Destroy` originally mentioned does currently work, and I've yet to notice negative side effects (though not certain GC is working as it should in this state).
