### ISSUE TITLE
[PostProcessScene] is not intended to be used outside the editor (and sometimes can't be)

### ISSUE THREAD

**Issue by giblet37** [PimDeWitte/UnityMainThreadDispatcher#6]
The April changes break compilation on some platforms (such as standalone windows) when building the application, instead of just running in the editor.  The entire UnityEditor package is not included in an actual executable, and can't be used in non-editor scripts.

**Comment by PimDeWitte** [comment]
Ok. Looking into this and possibly reverting that change. I'm considering making 1 editor script.

**Comment by jonathanleang** [comment]
ios build failed too

**Comment by PimDeWitte** [comment]
Reverted the master. Thanks for the reports guys.
