### ISSUE TITLE
Looking for info on making a Windows console server work within Unity using Dispatcher

### ISSUE THREAD

**Issue by MostHated** [PimDeWitte/UnityMainThreadDispatcher#7]
Hey there,
  I have a Windows console server application that uses things like ThreadPool, message Fibers, etc and I am trying to get it to work with Unity properly. It uses[ this fiber framework](https://github.com/chrisa23/Fibrous) and is quite complex, with a fairly large amount of interfaces and files associated with it that use things like Enqueue, IExecutor, Execute, toExecute, DispatchAdapter. Unfortunately, I am just not familiar enough with threading to be able to figure out exactly how to accomplish what I am after.

  I was able to get a test working using your UMTD. There was a place that used the call of "this.requestFiber.Enqueue(Method);" to, of course, queue up a method to run but when I would run the server within Unity it would not do anything once it ran it, so I took UMTD and just swapped it out for UnityMainThreadDispatcher.Instance().Enqueue(Method); and it worked. The only issue is, that was one single thing out of many, many places in which call Enqueue and I think that it kind of defeated the purpose of the whole fiber and enqueue system, to begin with by simply sending that one particular thing out to be processed. What I am trying to figure out / find information on is, in a system that uses Execute and things of that nature, is there a specific place I can / should put the UMTD to handle anything that is sent to be Enqueued so that I am not trying to go through the code and find everything that uses the Enqueue method and changing it to use the UMTD's Enqueue, or is that actually what I should do? I could technically just do a Find / Replace to anything using Enqueue, but that seems like it would not work well because of the "this.requestFiber" part of the call not being there anymore. 

 I am hoping that perhaps you might be able to give me an opinion or any info you might have? This is the very last part I need to get working in my game framework to finally be able to move on with my development, I have spent 2 months straight working on it and I am so close, yet I can't find any info on how to make this work the way I need. : (

Any assistance would be extremely appreciated!
Thanks,
-MH

**Comment by PimDeWitte** [comment]
Hello!

Since this is not related to the library I'm gonna have to close this as an issue. I am not familiar enough with Fiber and the other frameworks mentioned to give you a solid answer. I would recommend looking into other solutions as this library is just a fairly simple method to achieve a simple task. There are better ways not involving this library that can achieve the task you are mentioning.

All the best,
Pim

**Comment by MostHated** [comment]
That is not a problem, I figured it all out quite some time ago and just forgot to close this. 

Thanks,
-MH
